// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilbwzcigrdqozvptboqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYnd6Y2lncmRxb3p2cHRib3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMDIxMTUsImV4cCI6MjA4Njc3ODExNX0.sGgME3SZWOJVAYMI1GGANb_Mnqg9FFnj_YBo0-FrSS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});