// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aughkdwuvkgigczkfozp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1Z2hrZHd1dmtnaWdjemtmb3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Njc4OTUsImV4cCI6MjA2OTI0Mzg5NX0.S2c-cvGhbZl28GRXJPjGSk4KjBzhayNpkRg0STgYoJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});